name: Build and Deploy Unity Server

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/unity-server

jobs:

  build:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ github.sha }} \
            -t $IMAGE_NAME:latest .

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest


  deploy:
    needs: build
    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Kubernetes Resources
        run: |
          kubectl apply -f k8s/

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/unity-server \
            unity-server=$IMAGE_NAME:${{ github.sha }}

      - name: Wait For Rollout
        run: |
          kubectl rollout status deployment/unity-server